require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AsociadosController do

  # This should return the minimal set of attributes required to create a valid
  # Asociado. As you add validations to Asociado, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "imagen" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AsociadosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all asociados as @asociados" do
      asociado = Asociado.create! valid_attributes
      get :index, {}, valid_session
      assigns(:asociados).should eq([asociado])
    end
  end

  describe "GET show" do
    it "assigns the requested asociado as @asociado" do
      asociado = Asociado.create! valid_attributes
      get :show, {:id => asociado.to_param}, valid_session
      assigns(:asociado).should eq(asociado)
    end
  end

  describe "GET new" do
    it "assigns a new asociado as @asociado" do
      get :new, {}, valid_session
      assigns(:asociado).should be_a_new(Asociado)
    end
  end

  describe "GET edit" do
    it "assigns the requested asociado as @asociado" do
      asociado = Asociado.create! valid_attributes
      get :edit, {:id => asociado.to_param}, valid_session
      assigns(:asociado).should eq(asociado)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Asociado" do
        expect {
          post :create, {:asociado => valid_attributes}, valid_session
        }.to change(Asociado, :count).by(1)
      end

      it "assigns a newly created asociado as @asociado" do
        post :create, {:asociado => valid_attributes}, valid_session
        assigns(:asociado).should be_a(Asociado)
        assigns(:asociado).should be_persisted
      end

      it "redirects to the created asociado" do
        post :create, {:asociado => valid_attributes}, valid_session
        response.should redirect_to(Asociado.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved asociado as @asociado" do
        # Trigger the behavior that occurs when invalid params are submitted
        Asociado.any_instance.stub(:save).and_return(false)
        post :create, {:asociado => { "imagen" => "invalid value" }}, valid_session
        assigns(:asociado).should be_a_new(Asociado)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Asociado.any_instance.stub(:save).and_return(false)
        post :create, {:asociado => { "imagen" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested asociado" do
        asociado = Asociado.create! valid_attributes
        # Assuming there are no other asociados in the database, this
        # specifies that the Asociado created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Asociado.any_instance.should_receive(:update_attributes).with({ "imagen" => "MyString" })
        put :update, {:id => asociado.to_param, :asociado => { "imagen" => "MyString" }}, valid_session
      end

      it "assigns the requested asociado as @asociado" do
        asociado = Asociado.create! valid_attributes
        put :update, {:id => asociado.to_param, :asociado => valid_attributes}, valid_session
        assigns(:asociado).should eq(asociado)
      end

      it "redirects to the asociado" do
        asociado = Asociado.create! valid_attributes
        put :update, {:id => asociado.to_param, :asociado => valid_attributes}, valid_session
        response.should redirect_to(asociado)
      end
    end

    describe "with invalid params" do
      it "assigns the asociado as @asociado" do
        asociado = Asociado.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Asociado.any_instance.stub(:save).and_return(false)
        put :update, {:id => asociado.to_param, :asociado => { "imagen" => "invalid value" }}, valid_session
        assigns(:asociado).should eq(asociado)
      end

      it "re-renders the 'edit' template" do
        asociado = Asociado.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Asociado.any_instance.stub(:save).and_return(false)
        put :update, {:id => asociado.to_param, :asociado => { "imagen" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested asociado" do
      asociado = Asociado.create! valid_attributes
      expect {
        delete :destroy, {:id => asociado.to_param}, valid_session
      }.to change(Asociado, :count).by(-1)
    end

    it "redirects to the asociados list" do
      asociado = Asociado.create! valid_attributes
      delete :destroy, {:id => asociado.to_param}, valid_session
      response.should redirect_to(asociados_url)
    end
  end

end
